### ISSUE TITLE
这个--咋改--

### ISSUE THREAD

**Issue by dengxingze** [amehime/hexo-renderer-markdown-it-ex#3]
$ hexo g
INFO  Validating config
INFO  Start processing
Prism's Diff Highlight plugin requires the Diff language definition (prism-diff.js).Make sure the language definition is loaded or use Prism's Autoloader plugin.
INFO  Files loaded in 1.07 s
ERROR Template render error: (E:\blog\themes\shoka\layout\post.njk)
  Template render error: (E:\blog\themes\shoka\layout\post.njk)
  Template render error: (E:\blog\themes\shoka\layout\post.njk)
  Template render error: (E:\blog\themes\shoka\layout\post.njk) [Line 10, Column 98]
  Template render error: (E:\blog\themes\shoka\layout\post.njk) [Line 49, Column 29]
  Template render error: (E:\blog\themes\shoka\layout\post.njk) [Line 23, Column 18]
  Template render error: (E:\blog\themes\shoka\layout\post.njk) [Line 4, Column 46]
  Template render error: (E:\blog\themes\shoka\layout\post.njk)
  Template render error: (E:\blog\themes\shoka\layout\post.njk) [Line 5, Column 3]
  Template render error: (E:\blog\themes\shoka\layout\post.njk) [Line 29, Column 19]
  Template render error: (E:\blog\themes\shoka\layout\post.njk) [Line 38, Column 19]
  Template render error: (E:\blog\themes\shoka\layout\post.njk) [Line 42, Column 17]
  Template render error: (E:\blog\themes\shoka\layout\_partials\sidebar\overview.njk) [Line 45, Column 12]
  Template render error: (E:\blog\themes\shoka\layout\_partials\sidebar\menu.njk) [Line 3, Column 31]
  TypeError: Cannot read property 'replace' of undefined
    at Object._prettifyError (E:\blog\node_modules\nunjucks\src\lib.js:36:11)
    at E:\blog\node_modules\nunjucks\src\environment.js:561:19
    at Template.root [as rootRenderFunc] (eval at _compile (E:\blog\node_modules\nunjucks\src\environment.js:631:18), <anonymous>:57:3)
    at Template.render (E:\blog\node_modules\nunjucks\src\environment.js:550:10)
    at E:\blog\themes\shoka\scripts\renderer\njk.js:44:29
    at _View._compiled (E:\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
ERROR Template render error: (E:\blog\themes\shoka\layout\archive.njk)
  Template render error: (E:\blog\themes\shoka\layout\archive.njk) [Line 49, Column 29]
  Template render error: (E:\blog\themes\shoka\layout\archive.njk) [Line 23, Column 18]
  Template render error: (E:\blog\themes\shoka\layout\archive.njk)
  Template render error: (E:\blog\themes\shoka\layout\archive.njk)
  Template render error: (E:\blog\themes\shoka\layout\archive.njk) [Line 8, Column 5]
  Template render error: (E:\blog\themes\shoka\layout\archive.njk) [Line 18, Column 12]
  Template render error: (E:\blog\themes\shoka\layout\archive.njk) [Line 121, Column 22]
  Template render error: (E:\blog\themes\shoka\layout\archive.njk)
  Template render error: (E:\blog\themes\shoka\layout\_partials\pagination.njk)
  Template render error: (E:\blog\themes\shoka\layout\archive.njk) [Line 80, Column 46]
  Template render error: (E:\blog\themes\shoka\layout\_partials\sidebar\overview.njk) [Line 45, Column 12]
  Template render error: (E:\blog\themes\shoka\layout\_partials\sidebar\menu.njk) [Line 3, Column 31]
  TypeError: Cannot read property 'replace' of undefined
    at Object._prettifyError (E:\blog\node_modules\nunjucks\src\lib.js:36:11)
    at E:\blog\node_modules\nunjucks\src\environment.js:561:19
    at Template.root [as rootRenderFunc] (eval at _compile (E:\blog\node_modules\nunjucks\src\environment.js:631:18), <anonymous>:35:3)
    at Template.render (E:\blog\node_modules\nunjucks\src\environment.js:550:10)
    at E:\blog\themes\shoka\scripts\renderer\njk.js:44:29
    at _View._compiled (E:\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
ERROR Template render error: (E:\blog\themes\shoka\layout\archive.njk)
  Template render error: (E:\blog\themes\shoka\layout\archive.njk) [Line 49, Column 29]
  Template render error: (E:\blog\themes\shoka\layout\archive.njk) [Line 23, Column 18]
  Template render error: (E:\blog\themes\shoka\layout\archive.njk)
  Template render error: (E:\blog\themes\shoka\layout\archive.njk)
  Template render error: (E:\blog\themes\shoka\layout\archive.njk) [Line 8, Column 5]
  Template render error: (E:\blog\themes\shoka\layout\archive.njk) [Line 14, Column 80]
  Template render error: (E:\blog\themes\shoka\layout\archive.njk) [Line 121, Column 22]
  Template render error: (E:\blog\themes\shoka\layout\archive.njk)
  Template render error: (E:\blog\themes\shoka\layout\_partials\pagination.njk)
  Template render error: (E:\blog\themes\shoka\layout\archive.njk) [Line 80, Column 46]
  Template render error: (E:\blog\themes\shoka\layout\_partials\sidebar\overview.njk) [Line 45, Column 12]
  Template render error: (E:\blog\themes\shoka\layout\_partials\sidebar\menu.njk) [Line 3, Column 31]
  TypeError: Cannot read property 'replace' of undefined
    at Object._prettifyError (E:\blog\node_modules\nunjucks\src\lib.js:36:11)
    at E:\blog\node_modules\nunjucks\src\environment.js:561:19
    at Template.root [as rootRenderFunc] (eval at _compile (E:\blog\node_modules\nunjucks\src\environment.js:631:18), <anonymous>:35:3)
    at Template.render (E:\blog\node_modules\nunjucks\src\environment.js:550:10)
    at E:\blog\themes\shoka\scripts\renderer\njk.js:44:29
    at _View._compiled (E:\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
ERROR Template render error: (E:\blog\themes\shoka\layout\archive.njk)
  Template render error: (E:\blog\themes\shoka\layout\archive.njk) [Line 49, Column 29]
  Template render error: (E:\blog\themes\shoka\layout\archive.njk) [Line 23, Column 18]
  Template render error: (E:\blog\themes\shoka\layout\archive.njk)
  Template render error: (E:\blog\themes\shoka\layout\archive.njk)
  Template render error: (E:\blog\themes\shoka\layout\archive.njk) [Line 8, Column 5]
  Template render error: (E:\blog\themes\shoka\layout\archive.njk) [Line 16, Column 47]
  Template render error: (E:\blog\themes\shoka\layout\archive.njk) [Line 121, Column 22]
  Template render error: (E:\blog\themes\shoka\layout\archive.njk)
  Template render error: (E:\blog\themes\shoka\layout\_partials\pagination.njk)
  Template render error: (E:\blog\themes\shoka\layout\archive.njk) [Line 80, Column 46]
  Template render error: (E:\blog\themes\shoka\layout\_partials\sidebar\overview.njk) [Line 45, Column 12]
  Template render error: (E:\blog\themes\shoka\layout\_partials\sidebar\menu.njk) [Line 3, Column 31]
  TypeError: Cannot read property 'replace' of undefined
    at Object._prettifyError (E:\blog\node_modules\nunjucks\src\lib.js:36:11)
    at E:\blog\node_modules\nunjucks\src\environment.js:561:19
    at Template.root [as rootRenderFunc] (eval at _compile (E:\blog\node_modules\nunjucks\src\environment.js:631:18), <anonymous>:35:3)
    at Template.render (E:\blog\node_modules\nunjucks\src\environment.js:550:10)
    at E:\blog\themes\shoka\scripts\renderer\njk.js:44:29
    at _View._compiled (E:\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
ERROR Template render error: (E:\blog\themes\shoka\layout\page.njk)
  Template render error: (E:\blog\themes\shoka\layout\page.njk)
  Template render error: (E:\blog\themes\shoka\layout\page.njk)
  Template render error: (E:\blog\themes\shoka\layout\page.njk) [Line 49, Column 29]
  Template render error: (E:\blog\themes\shoka\layout\page.njk) [Line 23, Column 18]
  Template render error: (E:\blog\themes\shoka\layout\page.njk)
  Template render error: (E:\blog\themes\shoka\layout\page.njk)
  Template render error: (E:\blog\themes\shoka\layout\page.njk) [Line 6, Column 26]
  Template render error: (E:\blog\themes\shoka\layout\page.njk) [Line 24, Column 32]
  Template render error: (E:\blog\themes\shoka\layout\page.njk) [Line 40, Column 23]
  Template render error: (E:\blog\themes\shoka\layout\page.njk) [Line 69, Column 17]
  Template render error: (E:\blog\themes\shoka\layout\_partials\sidebar\overview.njk) [Line 45, Column 12]
  Template render error: (E:\blog\themes\shoka\layout\_partials\sidebar\menu.njk) [Line 3, Column 31]
  TypeError: Cannot read property 'replace' of undefined
    at Object._prettifyError (E:\blog\node_modules\nunjucks\src\lib.js:36:11)
    at E:\blog\node_modules\nunjucks\src\environment.js:561:19
    at Template.root [as rootRenderFunc] (eval at _compile (E:\blog\node_modules\nunjucks\src\environment.js:631:18), <anonymous>:51:3)
    at Template.render (E:\blog\node_modules\nunjucks\src\environment.js:550:10)
    at E:\blog\themes\shoka\scripts\renderer\njk.js:44:29
    at _View._compiled (E:\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
ERROR Template render error: (E:\blog\themes\shoka\layout\index.njk)
  Template render error: (E:\blog\themes\shoka\layout\index.njk)
  Template render error: (E:\blog\themes\shoka\layout\index.njk) [Line 10, Column 98]
  Template render error: (E:\blog\themes\shoka\layout\index.njk) [Line 29, Column 11]
  Template render error: (E:\blog\themes\shoka\layout\index.njk) [Line 49, Column 29]
  Template render error: (E:\blog\themes\shoka\layout\index.njk) [Line 23, Column 18]
  Template render error: (E:\blog\themes\shoka\layout\index.njk)
  Template render error: (E:\blog\themes\shoka\layout\index.njk)
  Template render error: (E:\blog\themes\shoka\layout\index.njk) [Line 9, Column 12]
  Template render error: (E:\blog\themes\shoka\layout\index.njk) [Line 35, Column 13]
  Template render error: (E:\blog\themes\shoka\layout\index.njk) [Line 35, Column 25]
  Template render error: (E:\blog\themes\shoka\layout\index.njk)
  Template render error: (E:\blog\themes\shoka\layout\_partials\pagination.njk)
  Template render error: (E:\blog\themes\shoka\layout\index.njk) [Line 80, Column 46]
  Template render error: (E:\blog\themes\shoka\layout\_partials\sidebar\overview.njk) [Line 45, Column 12]
  Template render error: (E:\blog\themes\shoka\layout\_partials\sidebar\menu.njk) [Line 3, Column 31]
  TypeError: Cannot read property 'replace' of undefined
    at Object._prettifyError (E:\blog\node_modules\nunjucks\src\lib.js:36:11)
    at E:\blog\node_modules\nunjucks\src\environment.js:561:19
    at Template.root [as rootRenderFunc] (eval at _compile (E:\blog\node_modules\nunjucks\src\environment.js:631:18), <anonymous>:45:3)
    at Template.render (E:\blog\node_modules\nunjucks\src\environment.js:550:10)
    at E:\blog\themes\shoka\scripts\renderer\njk.js:44:29
    at _View._compiled (E:\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
ERROR Template render error: (E:\blog\themes\shoka\layout\page.njk)
  Template render error: (E:\blog\themes\shoka\layout\page.njk)
  Template render error: (E:\blog\themes\shoka\layout\page.njk)
  Template render error: (E:\blog\themes\shoka\layout\page.njk) [Line 49, Column 29]
  Template render error: (E:\blog\themes\shoka\layout\page.njk) [Line 23, Column 18]
  Template render error: (E:\blog\themes\shoka\layout\page.njk)
  Template render error: (E:\blog\themes\shoka\layout\page.njk)
  Template render error: (E:\blog\themes\shoka\layout\page.njk) [Line 8, Column 26]
  Template render error: (E:\blog\themes\shoka\layout\page.njk) [Line 26, Column 32]
  Template render error: (E:\blog\themes\shoka\layout\page.njk) [Line 46, Column 19]
  Template render error: (E:\blog\themes\shoka\layout\page.njk) [Line 69, Column 17]
  Template render error: (E:\blog\themes\shoka\layout\_partials\sidebar\overview.njk) [Line 45, Column 12]
  Template render error: (E:\blog\themes\shoka\layout\_partials\sidebar\menu.njk) [Line 3, Column 31]
  TypeError: Cannot read property 'replace' of undefined
    at Object._prettifyError (E:\blog\node_modules\nunjucks\src\lib.js:36:11)
    at E:\blog\node_modules\nunjucks\src\environment.js:561:19
    at Template.root [as rootRenderFunc] (eval at _compile (E:\blog\node_modules\nunjucks\src\environment.js:631:18), <anonymous>:51:3)
    at Template.render (E:\blog\node_modules\nunjucks\src\environment.js:550:10)
    at E:\blog\themes\shoka\scripts\renderer\njk.js:44:29
    at _View._compiled (E:\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
ERROR Template render error: (E:\blog\themes\shoka\layout\page.njk)
  Template render error: (E:\blog\themes\shoka\layout\page.njk)
  Template render error: (E:\blog\themes\shoka\layout\page.njk)
  Template render error: (E:\blog\themes\shoka\layout\page.njk) [Line 49, Column 29]
  Template render error: (E:\blog\themes\shoka\layout\page.njk) [Line 23, Column 18]
  Template render error: (E:\blog\themes\shoka\layout\page.njk)
  Template render error: (E:\blog\themes\shoka\layout\page.njk)
  Template render error: (E:\blog\themes\shoka\layout\page.njk) [Line 10, Column 8]
  Template render error: (E:\blog\themes\shoka\layout\page.njk) [Line 28, Column 14]
  Template render error: (E:\blog\themes\shoka\layout\page.njk) [Line 58, Column 31]
  Template render error: (E:\blog\themes\shoka\layout\page.njk) [Line 69, Column 17]
  Template render error: (E:\blog\themes\shoka\layout\_partials\sidebar\overview.njk) [Line 45, Column 12]
  Template render error: (E:\blog\themes\shoka\layout\_partials\sidebar\menu.njk) [Line 3, Column 31]
  TypeError: Cannot read property 'replace' of undefined
    at Object._prettifyError (E:\blog\node_modules\nunjucks\src\lib.js:36:11)
    at E:\blog\node_modules\nunjucks\src\environment.js:561:19
    at Template.root [as rootRenderFunc] (eval at _compile (E:\blog\node_modules\nunjucks\src\environment.js:631:18), <anonymous>:51:3)
    at Template.render (E:\blog\node_modules\nunjucks\src\environment.js:550:10)
    at E:\blog\themes\shoka\scripts\renderer\njk.js:44:29
    at _View._compiled (E:\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
INFO  Generated: archives/2021/index.html
INFO  Generated: archives/index.html
INFO  Generated: categories/index.html
INFO  Generated: tags/index.html
(node:6336) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6336) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:6336) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:6336) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:6336) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:6336) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
INFO  Generated: index.html
INFO  Generated: 404.html
INFO  Generated: archives/2021/01/index.html
INFO  Generated: images/404.png
INFO  Generated: images/algolia_logo.svg
INFO  Generated: images/failure.ico
INFO  Generated: images/logo.svg
INFO  Generated: images/favicon.ico
INFO  Generated: images/play_needle.png
INFO  Generated: images/play_disc.png
INFO  Generated: images/search.png
INFO  Generated: images/avatar.jpg
INFO  Generated: images/apple-touch-icon.png
INFO  Generated: images/alipay.png
INFO  Generated: images/paypal.png
INFO  Generated: images/wechatpay.png
INFO  Generated: css/mermaid.css
INFO  Generated: 2021/01/08/hello-world/index.html
INFO  Generated: js/app.js
INFO  Generated: css/comment.css
INFO  Generated: css/app.css
INFO  25 files generated in 2.54 s

**Comment by LXYOvO** [comment]
这应该是搜索插件没有配置好，把搜索插件删了试试。

**Comment by HMJ-Modesty** [comment]
咋修好的？
